name: jarvis-command
on:
    repository_dispatch:
        types: [jarvis-command]
jobs:
    jarvis:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.client_payload.pull_request.head.ref }}
                  fetch-depth: 0

            - name: Get Help
              uses: peter-evans/create-or-update-comment@v3
              if: startsWith(github.event.client_payload.slash_command.args.all, 'help')
              with:
                  token: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
                  comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
                  body: |
                      > Command | Description
                      > --- | ---
                      > /hello | echo world
                  reactions: heart

            - name: Hello Jarvis
              uses: peter-evans/create-or-update-comment@v3
              if: startsWith(github.event.client_payload.slash_command.args.all, 'hello')
              with:
                  token: ${{ secrets.ACTIONS_BOT_TOKEN }}
                  repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
                  comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
                  body: |
                      world!
                  reactions: laugh
